# Generated by Django 4.2.30 on 2026-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(
                blank=True, help_text="Main note text (Markdown supported).", null=True
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF, image or Word file.",
                null=True,
                upload_to="notes_file/",
            ),
        ),
    ]
