# Generated by Django 4.2.30 on 2026-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_course_updated_note_content_note_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.AddField(
            model_name="note",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, help_text="Main note text.", null=True),
        ),
    ]
