# Generated by Django 4.2.30 on 2026-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_note_user_note_description_alter_note_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
